apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  creationTimestamp: null
  name: cert-manager
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec: {}