---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    operators.coreos.com/external-secrets-operator.openshift-operators: ''
  name: external-secrets-operator
  namespace: olm
spec:
  channel: stable
  installPlanApproval: Automatic
  name: external-secrets-operator
  source: operatorhubio-catalog
  sourceNamespace: olm