---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/kenmoini/kn-k8s-deploy'
    targetRevision: HEAD
    path: manifests/external-secrets-operator
    kustomize:
      version: v4.4.1
  project: cluster-apps
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: false # overrides changes made on the cluster that drift from git state
