apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: openshift-gitops
spec:
  project: helm-installed
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.7.2
    helm:
      releaseName: sealed-secrets
      #valueFiles:
      #- values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: false # overrides changes made on the cluster that drift from git state
    syncOptions:
      - CreateNamespace=true